import { int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull() });
export const clients = mysqlTable("clients", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), companyName: varchar("companyName", { length: 180 }), phone: varchar("phone", { length: 32 }), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const projects = mysqlTable("projects", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 180 }).notNull(), description: text("description"), type: varchar("type", { length: 80 }), location: varchar("location", { length: 180 }), phase: varchar("phase", { length: 80 }), progress: int("progress").default(0).notNull(), status: mysqlEnum("status", ["draft", "active", "completed"]).default("draft").notNull(), coverUrl: text("coverUrl"), coverKey: varchar("coverKey", { length: 500 }), isFeatured: int("isFeatured").default(0).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const projectClients = mysqlTable("projectClients", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), clientId: int("clientId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const diaryEntries = mysqlTable("diaryEntries", { id: int("id").autoincrement().primaryKey(), projectId: int("projectId").notNull(), title: varchar("title", { length: 180 }).notNull(), description: text("description").notNull(), phase: varchar("phase", { length: 80 }), progress: int("progress").default(0).notNull(), entryDate: timestamp("entryDate").notNull(), createdBy: int("createdBy").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const diaryPhotos = mysqlTable("diaryPhotos", { id: int("id").autoincrement().primaryKey(), entryId: int("entryId").notNull(), storageKey: varchar("storageKey", { length: 500 }).notNull(), url: text("url").notNull(), altText: varchar("altText", { length: 180 }), createdAt: timestamp("createdAt").defaultNow().notNull() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;
export type Client = typeof clients.$inferSelect; export type Project = typeof projects.$inferSelect; export type DiaryEntry = typeof diaryEntries.$inferSelect;
