import { useState } from "react";
import { Link } from "wouter";
import { ArrowRight, Building2, Check, ChevronRight, LockKeyhole, MapPin, Menu, Phone, Ruler, ShieldCheck, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";

const works = [
  { title: "Casa Aroeira", type: "Residencial", location: "Nova Lima · MG", phase: "Acabamentos", progress: 82, image: "/images/obra-01.jpg", tone: "dark" },
  { title: "Sede Horizonte", type: "Corporativo", location: "Belo Horizonte · MG", phase: "Estrutura", progress: 54, image: "/images/obra-02.jpg", tone: "light" },
  { title: "Pátio 48", type: "Comercial", location: "São Paulo · SP", phase: "Fundação", progress: 28, image: "/images/obra-03.jpg", tone: "light" },
];

function Brand({ inverse = false }: { inverse?: boolean }) {
  return <div className={`flex items-center gap-3 ${inverse ? "text-white" : "text-neutral-950"}`}><div className="relative h-10 w-10 shrink-0"><span className={`absolute left-0 top-3 h-3 w-8 -rotate-39 ${inverse ? "bg-white" : "bg-neutral-950"}`} /><span className="absolute right-0 top-0 h-3 w-10 rotate-48 bg-[#c99709]" /><span className={`absolute bottom-0 right-0 h-3 w-7 rotate-48 ${inverse ? "bg-white" : "bg-[#c99709]"}`} /></div><div className="leading-none"><div className="font-display text-[17px] font-extrabold tracking-[-.06em]">ORIGINAL TECH</div><div className="mt-1 text-[9px] font-semibold tracking-[.01em]">Soluções em Engenharia e Arquitetura</div></div></div>
}

function WorkCard({ work }: { work: typeof works[number] }) {
  return <article className="group overflow-hidden rounded-2xl border border-[#dfddd6] bg-white shadow-[0_15px_40px_rgba(26,25,20,.06)]"><div className="relative h-64 overflow-hidden"><img src={work.image} alt={work.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/5 to-transparent" /><div className="absolute left-5 top-5 rounded-full bg-white/90 px-3 py-1 text-[11px] font-bold uppercase tracking-[.14em] text-neutral-700">{work.type}</div><div className="absolute bottom-5 left-5 right-5 flex items-end justify-between text-white"><div><h3 className="font-display text-2xl font-bold">{work.title}</h3><p className="mt-1 flex items-center gap-1.5 text-sm text-white/80"><MapPin size={13} />{work.location}</p></div><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#c99709] text-neutral-950"><ArrowRight size={18} /></span></div></div><div className="p-5"><div className="mb-3 flex items-center justify-between text-sm"><span className="text-neutral-500">Etapa atual</span><span className="font-semibold text-neutral-900">{work.phase}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-[#ebe9e2]"><div className="h-full rounded-full bg-[#c99709]" style={{ width: `${work.progress}%` }} /></div><div className="mt-3 flex justify-between text-xs text-neutral-500"><span>Progresso da execução</span><span className="font-bold text-[#9a7300]">{work.progress}%</span></div></div></article>
}

export default function Home() {
  const [loginOpen, setLoginOpen] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  return <div className="min-h-screen overflow-x-hidden bg-[#f7f6f2]">
    <header className="absolute inset-x-0 top-0 z-20"><div className="container flex h-24 items-center justify-between"><Brand inverse /><nav className="hidden items-center gap-8 text-sm font-medium text-white/80 md:flex"><a href="#empresa" className="transition hover:text-white">A empresa</a><a href="#servicos" className="transition hover:text-white">Serviços</a><a href="#obras" className="transition hover:text-white">Obras</a><a href="#contato" className="transition hover:text-white">Contato</a></nav><div className="hidden md:block"><Button onClick={() => setLoginOpen(true)} className="rounded-full bg-[#c99709] px-5 font-semibold text-neutral-950 hover:bg-[#dfb62e]"><LockKeyhole size={15} className="mr-2" />Área do cliente</Button></div><button className="text-white md:hidden" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</button></div>{mobileOpen && <div className="border-t border-white/10 bg-[#111]/95 p-5 md:hidden"><div className="flex flex-col gap-4 text-white"><a href="#empresa" onClick={() => setMobileOpen(false)}>A empresa</a><a href="#servicos" onClick={() => setMobileOpen(false)}>Serviços</a><a href="#obras" onClick={() => setMobileOpen(false)}>Obras</a><Button onClick={() => setLoginOpen(true)} className="mt-2 bg-[#c99709] text-black">Área do cliente</Button></div></div>}</header>
    <main>
      <section className="hero-grid relative min-h-[690px] overflow-hidden bg-[#121212] text-white"><div className="absolute -right-24 top-24 h-[520px] w-[520px] rounded-full bg-[#c99709]/10 blur-3xl" /><div className="container relative grid min-h-[690px] items-center gap-10 py-32 lg:grid-cols-[1.08fr_.92fr]"><div className="reveal max-w-2xl"><div className="mb-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[.23em] text-[#d6a91e]"><span className="h-px w-10 bg-[#c99709]" /> Engenharia que permanece</div><h1 className="font-display text-5xl font-extrabold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-[76px]">Projetamos espaços.<br /><span className="text-[#d2a313]">Construímos futuros.</span></h1><p className="mt-8 max-w-lg text-lg leading-relaxed text-white/65">Soluções em engenharia e arquitetura para projetos que unem precisão técnica, estética e o cuidado de quem constrói para durar.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#obras"><Button className="rounded-full bg-[#c99709] px-6 py-6 font-semibold text-neutral-950 hover:bg-[#dfb62e]">Conheça nossas obras <ArrowRight size={17} className="ml-2" /></Button></a><a href="#contato"><Button variant="outline" className="rounded-full border-white/25 bg-transparent px-6 py-6 text-white hover:bg-white/10 hover:text-white">Fale com a nossa equipe</Button></a></div></div><div className="relative hidden h-[450px] lg:block"><div className="absolute right-0 top-3 h-[410px] w-[82%] overflow-hidden rounded-[2px] border border-white/10"><img src="/images/obra-02.jpg" className="h-full w-full object-cover opacity-80" alt="Arquitetura contemporânea" /><div className="absolute inset-0 bg-gradient-to-tr from-black/60 via-transparent to-[#c99709]/10" /></div><div className="absolute bottom-0 left-0 w-56 border-l-2 border-[#c99709] bg-[#191919] p-5"><div className="font-display text-4xl font-bold text-[#d2a313]">12+</div><div className="mt-1 text-xs uppercase tracking-[.15em] text-white/60">anos transformando ideias em obra</div></div><div className="absolute right-0 top-[-10px] flex h-20 w-20 items-center justify-center rounded-full border border-[#c99709]/50 bg-[#c99709]/10 text-[#d2a313]"><Sparkles size={24} /></div></div></div><div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-[#c99709] to-transparent opacity-50" /></section>
      <section id="empresa" className="container grid gap-12 py-24 lg:grid-cols-[.8fr_1.2fr] lg:py-32"><div><div className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#a07800]">Quem somos</div><h2 className="font-display text-4xl font-bold leading-tight tracking-[-.04em] sm:text-5xl">Precisão em cada<br /><span className="text-[#b78600]">linha do projeto.</span></h2></div><div className="max-w-2xl"><p className="text-xl leading-relaxed text-neutral-700">A Original Tech nasceu para aproximar o rigor da engenharia da sensibilidade da arquitetura. Desenvolvemos e executamos projetos com visão integral — do primeiro traço à entrega das chaves.</p><div className="mt-10 grid gap-5 border-t border-[#dfddd6] pt-7 sm:grid-cols-3"><div><div className="font-display text-3xl font-bold">48</div><div className="mt-1 text-sm text-neutral-500">obras entregues</div></div><div><div className="font-display text-3xl font-bold">96%</div><div className="mt-1 text-sm text-neutral-500">clientes recorrentes</div></div><div><div className="font-display text-3xl font-bold">MG · SP</div><div className="mt-1 text-sm text-neutral-500">atuação nacional</div></div></div></div></section>
      <section id="servicos" className="bg-[#ece9e0] py-24"><div className="container"><div className="mb-12 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#a07800]">Como atuamos</div><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Do conceito à entrega.</h2></div><p className="max-w-sm text-sm leading-relaxed text-neutral-600">Uma equipe multidisciplinar para cuidar de cada decisão com clareza, método e comprometimento.</p></div><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#171717] p-7 text-white"><Ruler className="mb-12 text-[#d2a313]" size={28} /><h3 className="font-display text-2xl font-bold">Projetos & Arquitetura</h3><p className="mt-3 text-sm leading-relaxed text-white/55">Projetos autorais, funcionais e alinhados ao contexto de cada cliente.</p><div className="mt-8 flex items-center gap-2 text-sm font-semibold text-[#d2a313]">Explorar serviço <ChevronRight size={15} /></div></div><div className="rounded-2xl border border-[#d6d2c8] bg-white p-7"><Building2 className="mb-12 text-[#b78600]" size={28} /><h3 className="font-display text-2xl font-bold">Execução de Obras</h3><p className="mt-3 text-sm leading-relaxed text-neutral-600">Planejamento, gestão e execução com controle de qualidade em todas as etapas.</p><div className="mt-8 flex items-center gap-2 text-sm font-semibold text-[#9a7300]">Explorar serviço <ChevronRight size={15} /></div></div><div className="rounded-2xl border border-[#d6d2c8] bg-white p-7"><ShieldCheck className="mb-12 text-[#b78600]" size={28} /><h3 className="font-display text-2xl font-bold">Gestão & Consultoria</h3><p className="mt-3 text-sm leading-relaxed text-neutral-600">Decisões técnicas mais seguras, transparentes e orientadas a resultados.</p><div className="mt-8 flex items-center gap-2 text-sm font-semibold text-[#9a7300]">Explorar serviço <ChevronRight size={15} /></div></div></div></div></section>
      <section id="obras" className="container py-24 lg:py-32"><div className="mb-12 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#a07800]">Portfólio selecionado</div><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Obras em destaque.</h2></div><a href="#contato" className="flex items-center gap-2 text-sm font-bold text-[#9a7300] hover:text-neutral-950">Ver todos os projetos <ArrowRight size={16} /></a></div><div className="grid gap-6 lg:grid-cols-3">{works.map(work => <WorkCard key={work.title} work={work} />)}</div></section>
      <section className="bg-[#171717] py-24 text-white"><div className="container grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#d2a313]">Acompanhamento transparente</div><h2 className="max-w-2xl font-display text-4xl font-bold leading-tight tracking-[-.04em] sm:text-5xl">Sua obra, acompanhada<br /><span className="text-[#d2a313]">em cada detalhe.</span></h2><p className="mt-5 max-w-xl text-white/55">No Portal Original Tech, clientes acompanham o avanço do projeto, consultam registros e visualizam o diário de obras com fotos e atualizações.</p></div><Button onClick={() => setLoginOpen(true)} className="w-fit rounded-full bg-[#c99709] px-7 py-6 font-semibold text-neutral-950 hover:bg-[#dfb62e]">Acessar meu portal <LockKeyhole size={16} className="ml-2" /></Button></div></section>
      <section id="contato" className="container grid gap-10 py-24 lg:grid-cols-[1fr_.8fr]"><div><div className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-[#a07800]">Vamos conversar</div><h2 className="font-display text-4xl font-bold tracking-[-.04em] sm:text-5xl">Seu próximo projeto<br /><span className="text-[#b78600]">começa aqui.</span></h2></div><div className="lg:pt-9"><p className="text-neutral-600">Conte um pouco sobre o que você deseja construir. Nossa equipe retorna para entender o desafio e apresentar o melhor caminho.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button className="rounded-full bg-neutral-950 px-6 py-6 text-white hover:bg-neutral-800"><Phone size={16} className="mr-2" /> (31) 3333-0000</Button><Button variant="outline" className="rounded-full border-neutral-300 px-6 py-6">Enviar briefing <ArrowRight size={16} className="ml-2" /></Button></div></div></section>
    </main><footer className="border-t border-[#dfddd6] py-8"><div className="container flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><Brand /><p className="text-xs text-neutral-500">© 2026 Original Tech. Engenharia com propósito.</p></div></footer>
    {loginOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"><div className="relative w-full max-w-md rounded-2xl bg-white p-8 shadow-2xl"><button onClick={() => setLoginOpen(false)} className="absolute right-5 top-5 text-neutral-400 hover:text-black"><X size={18} /></button><div className="mb-8"><div className="mb-5 inline-flex h-11 w-11 items-center justify-center rounded-full bg-[#f5edda] text-[#a07800]"><LockKeyhole size={20} /></div><h3 className="font-display text-2xl font-bold">Acesse seu portal</h3><p className="mt-2 text-sm text-neutral-500">Entre para acompanhar suas obras em tempo real.</p></div><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-neutral-500">E-mail</label><input className="mb-4 h-12 w-full rounded-lg border border-neutral-200 px-4 outline-none focus:border-[#c99709]" placeholder="seu@email.com" /><label className="mb-2 block text-xs font-bold uppercase tracking-wider text-neutral-500">Senha</label><input type="password" className="h-12 w-full rounded-lg border border-neutral-200 px-4 outline-none focus:border-[#c99709]" placeholder="••••••••" /><Link href="/portal"><Button onClick={() => setLoginOpen(false)} className="mt-6 h-12 w-full rounded-lg bg-neutral-950 text-white hover:bg-neutral-800">Entrar no portal <ArrowRight size={16} className="ml-2" /></Button></Link><p className="mt-5 text-center text-xs text-neutral-400">Problemas para acessar? Fale com o suporte.</p></div></div>}
  </div>
}
